name: dart_study
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  intl: ^0.20.2
  csv: ^5.0.2
  yaml: ^3.1.2
  http: ^1.2.0
  
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
